### ISSUE TITLE
Une seule route s'affiche

### ISSUE THREAD

**Issue by rouvoy** [APISENSE/afnic2015#1]
Le nombre de traces est bien incrémenté mais le nombre de route affichées reste limité à une seule alors  que le lieu d'émission de la requête est différent.

**Comment by duribreux** [comment]
Ne spam pas, je check ça sans doute pendant le weekend. Il y a une erreur qui pop dans les log de la page, je regarderai ça.

**Comment by duribreux** [comment]
Aucune des IPs récupérées via ton traceroute n'a réussi à être reverse ce qui faisait planté mon script JS  et empêchait l'affichage de ta coordonnées. Le problème a été fix.
J'en ai également profité pour ajouter une trace depuis chez moi (avec l'émulateur). Je finis sur un serveur à Grenoble (seule IP résolue) et mon traceroute est ISO avec celui de mon système.

Néanmoins, tes traces semblent bien plus chaotiques au niveau des TTL (problème d'exécution en parallèle ?) (http://apisense.io/api/v1/lQwJQPVzevC9aXxOvVqO/data) et j'imagine que le script a encore spam à cause de la géoloc. Il va vraiment falloir faire une méthode qui fait un fix GPS et s'arrête...
